export const teamMembers = [
    {
        code: 1,
        name: "Aurélio Bordalo",
        position: "Sócio Diretor(a), Bordalo Imob",
        comercial: "(61) 2195-0060",
        celular: "(61) 99381-7118",
        whatsapp: "(61) 99381-7118",
        email: "",
        image: "public/images/aureliobordalo.jpg"
    },
    {
        code: 2,
        name: "Danielle Christina",
        position: "Sócio Diretor(a), Bordalo Imob",
        comercial: "(61) 2195-0060",
        celular: "(61) 9381-7124",
        whatsapp: "(61) 9381-7124",
        email: "danielle@bordaloimob.com.br",
        image: "public/images/DanielleChristina.jpg"
    },
    {
        code: 3,
        name: "Sheila Antunes",
        position: "Gerente Administrativo, Bordalo Imob",
        comercial: "(61) 2195-0060",
        celular: "",
        whatsapp: "",
        email: "",
        image: "public/images/SheilaAntunes.jpg"
    },
    {
        code: 4,
        name: "Igor Martins",
        position: "Auxiliar Administrativo, Bordalo Imob",
        comercial: "(61) 2195-0060",
        celular: "",
        whatsapp: "",
        email: "",
        image: "public/images/IgorMartins.jpg"
    },
    {
        code: 5,
        name: "Lucas Bordalo",
        position: "Corretor de Imóveis, Bordalo Imob",
        comercial: "(61) 2195-0060",
        celular: "(61) 99362-4694",
        whatsapp: "(61) 99362-4694",
        email: "lbordalo1994@gmail.com",
        image: "public/images/LucasBordalo.jpg"
    },
    {
        code: 6,
        name: "Yasmim Cristiele",
        position: "Recepcionista, Bordalo Imob",
        comercial: "(61) 2195-0060",
        celular: "",
        whatsapp: "",
        email: "",
        image: "public/images/YasmimCristiele.jpg"
    },
    {
        code: 8,
        name: "Gabriel Oliveira Rebouças",
        position: "",
        Url: "gabriel",
        comercial: "(61)2195-0060",
        celular: "(61) 99175-5874",
        whatsapp:"(61) 99227-9871",
        email: "gabriel.bordaloimob@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 9,
        name: "Matheus Silva De Mello",
        position: "",
        Url: "matheus",
        comercial: "(61) 2195-0060",
        celular: "(61) 99834-0067",
        whatsapp:"(61) 99834-0067",
        email: "mtsmello0@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 10,
        name: "Camilla Teixeira Bordalo",
        position: "",
        Url: "camilla",
        comercial: "(61) 2195-0060",
        celular: "(61) 99682-0707",
        whatsapp:"(61) 99682-0707",
        email: "camillabordalocorretora@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 11,
        name: "Gelzileide de Macedo Neto",
        position: "",
        Url: "leide",
        comercial: "(61) 2195-0060",
        celular: "(61) 98623-3434",
        whatsapp:"(61) 98623-3434",
        email: "leidemacedo.adm@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 12,
        name: "Felipe Santos Assunção",
        position: "",
        Url: "felipe",
        comercial: "(61) 2195-0060",
        celular: "(61) 99586-0223",
        whatsapp:"(61) 99586-0223",
        email: "felipeassuncaobsb@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 13,
        name: "Juliana Vieira",
        position: "",
        Url: "juliana",
        comercial: "(61) 2195-0060",
        celular: "(61) 98272-2371",
        whatsapp:"(61) 98272-2371",
        email: "anailujv@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 14,
        name: "Rozane Bastos Domingues Horine",
        position: "",
        Url: "rozane",
        comercial: "(61) 2195-0060",
        celular: "(61) 99914-0383",
        whatsapp:"(61) 99914-0383",
        email: "rozanehorine@gmail.com",
        URLImagem: "RozaneHorine.jpg"
    },
    {
        code: 15,
        name: "Magna Adriana Soares Costa",
        position: "",
        Url: "magna",
        comercial: "(61) 2195-0060",
        celular: "(61) 98299-1728",
        whatsapp:"(61) 98299-1728",
        email: "magna.veloxlavanderia@gmail",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 16,
        name: "Mariana vilas Boas",
        position: "",
        Url: "mariana",
        comercial: "",
        celular: "(61) 98350–5200",
        whatsapp:"(61) 98350–5200",
        email: "vilasboasimob@gmail.com",
        URLImagem: "Mari.jpeg"
    },
    {
        code: 17,
        name: "André Luiz Simplício",
        position: "",
        Url: "andreluiz",
        comercial: "",
        celular: "(61) 98445-7715",
        whatsapp:"(61) 98445-7715",
        email: "Simplicioimoveis@gmail.com",
        URLImagem: "Simplicio.jpeg"
    },
    {
        code: 18,
        name: "André Henrique O Costa",
        position: "",
        Url: "andrecosta",
        comercial: "",
        celular: "(61) 98265-8896",
        whatsapp:"(61) 98265-8896",
        email: "costa0001@hotmail.com",
        URLImagem: "andrecosta.jpg"
    },
    {
        code: 19,
        name: "Gustavo Motta",
        position: "",
        Url: "gustavo",
        comercial: "",
        celular: "(61) 99858-7237",
        whatsapp:"(61) 998558-7237",
        email: "Mottg16@gmail.com",
        URLImagem: "gustavodeaguiar.jpg"
    },
    {
        code: 20,
        name: "Pollyana Xavier do Amaral",
        position: "",
        Url: "pollyana",
        comercial: "",
        celular: "(61) 98241-8900",
        whatsapp:"(61) 98241-8900",
        email: "Pollyamaral@hotmail.com",
        URLImagem: "PollyanaXavier.jpg"
    },
    {
        code: 21,
        name: "André Duarte",
        position: "",
        Url: "andreduarte",
        comercial: "",
        celular: "(61) 98607-0007",
        whatsapp:"(61) 98607-0007",
        email: "pr.andreduarte@gmail.com",
        URLImagem: "andreduarte.jpg"
    },
    {
        code: 22,
        name: "Esmeralda Rodrigues dos Santos",
        position: "",
        Url: "esmeralda",
        comercial: "",
        celular: "(61) 99142-0603",
        whatsapp:"(61) 99142-0603",
        email: "esmeralda.correta@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 23,
        name: "Sueli Simões da Silva",
        position: "",
        Url: "sueli",
        comercial: "",
        celular: "(61) 99629-8316",
        whatsapp:"(61) 99629-8316",
        email: "Suelyysimoes@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 24,
        name: "Ferix Antònio Orro Neto",
        position: "",
        Url: "ferix",
        comercial: "",
        celular: "(61) 99149-1751",
        whatsapp:"(61) 99629-8316",
        email: "faoneto84@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 25,
        name: "José Rodrigo de Paulo",
        position: "",
        Url: "rodrigo",
        comercial: "",
        celular: "(61) 98140-0071",
        whatsapp:"(61) 98140-0071",
        email: "rodrigodepaulo.correto@gmail.com",
        URLImagem: "RodrigodePaulo.jpg"
    },
    {
        code: 26,
        name: "Fabiana vilas boas de Almeida",
        position: "",
        Url: "fabiana",
        comercial: "",
        celular: "(61) 99988-2018",
        whatsapp:"(61) 99988-2018",
        email: "Fabiana.vba@gmail.com",
        //URLImagem: "~/Content/imgs/equipe/RozaneHorine.jpg"
    },
    {
        code: 27,
        name: "Tatiane da Silva Lopes",
        position: "",
        Url: "tatiane",
        comercial: "",
        celular: "(61) 99562-6688",
        whatsapp:"(61) 99562-6688",
        email: "tat.slopes@gmail.com",
        URLImagem: "TatianadaSilva.jpg"
    }
]